// Package gripmock_sdk_go provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package gripmock_sdk_go

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	gptypes "github.com/bavix/gripmock/v3/internal/infra/types"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
	codes "google.golang.org/grpc/codes"
)

// AddDescriptorsResponse defines model for AddDescriptorsResponse.
type AddDescriptorsResponse struct {
	Message string `json:"message"`

	// ServiceIDs Service IDs (e.g. helloworld.Greeter) registered. Use DELETE /services/{serviceID} to remove.
	ServiceIDs []string  `json:"serviceIDs"`
	Time       time.Time `json:"time"`
}

// CallRecord defines model for CallRecord.
type CallRecord struct {
	Error     *string                 `json:"error,omitempty"`
	Method    *string                 `json:"method,omitempty"`
	Request   *map[string]interface{} `json:"request,omitempty"`
	Response  *map[string]interface{} `json:"response,omitempty"`
	Service   *string                 `json:"service,omitempty"`
	StubId    *string                 `json:"stubId,omitempty"`
	Timestamp *time.Time              `json:"timestamp,omitempty"`
}

// DescriptorServiceIDs defines model for DescriptorServiceIDs.
type DescriptorServiceIDs struct {
	// ServiceIDs Service IDs added via POST /descriptors
	ServiceIDs []string `json:"serviceIDs"`
}

// HistoryList defines model for HistoryList.
type HistoryList = []CallRecord

// ID defines model for ID.
type ID = openapi_types.UUID

// ListID defines model for ListID.
type ListID = []ID

// McpError defines model for McpError.
type McpError struct {
	Code    int            `json:"code"`
	Data    map[string]any `json:"data,omitempty"`
	Message string         `json:"message"`
}

// McpID defines model for McpID.
type McpID struct {
	union json.RawMessage
}

// McpID0 defines model for .
type McpID0 = string

// McpID1 defines model for .
type McpID1 = int

// McpInfoResponse defines model for McpInfoResponse.
type McpInfoResponse struct {
	Methods         []string     `json:"methods"`
	ProtocolVersion string       `json:"protocolVersion"`
	ServerName      string       `json:"serverName"`
	ServerVersion   string       `json:"serverVersion"`
	Tools           []McpTool    `json:"tools"`
	Transport       McpTransport `json:"transport"`
}

// McpRequest defines model for McpRequest.
type McpRequest struct {
	Id      *McpID         `json:"id,omitempty"`
	Jsonrpc string         `json:"jsonrpc"`
	Method  string         `json:"method"`
	Params  map[string]any `json:"params,omitempty"`
}

// McpResponse defines model for McpResponse.
type McpResponse struct {
	Error   *McpError      `json:"error,omitempty"`
	Id      *McpID         `json:"id,omitempty"`
	Jsonrpc string         `json:"jsonrpc"`
	Result  map[string]any `json:"result,omitempty"`
}

// McpTool defines model for McpTool.
type McpTool struct {
	Description string         `json:"description"`
	InputSchema map[string]any `json:"inputSchema"`
	Name        string         `json:"name"`
}

// McpTransport defines model for McpTransport.
type McpTransport struct {
	Methods []string `json:"methods"`
	Path    string   `json:"path"`
}

// MessageOK defines model for MessageOK.
type MessageOK struct {
	Message string    `json:"message"`
	Time    time.Time `json:"time"`
}

// Method defines model for Method.
type Method struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// SearchRequest defines model for SearchRequest.
type SearchRequest struct {
	Data    interface{}       `json:"data"`
	Headers map[string]string `json:"headers,omitempty"`
	Id      *ID               `json:"id,omitempty"`
	Method  string            `json:"method"`
	Service string            `json:"service"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Code    codes.Code        `json:"code,omitempty"`
	Data    interface{}       `json:"data"`
	Error   string            `json:"error"`
	Headers map[string]string `json:"headers,omitempty"`
}

// Service defines model for Service.
type Service struct {
	Id      string   `json:"id"`
	Methods []Method `json:"methods"`
	Name    string   `json:"name"`
	Package string   `json:"package"`
}

// Stub defines model for Stub.
type Stub struct {
	Headers StubHeaders `json:"headers,omitempty"`
	Id      *ID         `json:"id,omitempty"`
	Input   StubInput   `json:"input"`

	// Inputs Inputs to match against. If multiple inputs are provided, the stub will be matched if any of the inputs match.
	Inputs []StubInput `json:"inputs,omitempty"`
	Method string      `json:"method"`

	// Options Optional behavior settings for a stub
	Options *StubOptions `json:"options,omitempty"`
	Output  StubOutput   `json:"output"`

	// Priority Priority of the stub. Higher priority stubs are matched first.
	Priority int    `json:"priority,omitempty"`
	Service  string `json:"service"`
}

// StubHeaders defines model for StubHeaders.
type StubHeaders struct {
	Contains map[string]string `json:"contains,omitempty"`
	Equals   map[string]string `json:"equals,omitempty"`
	Matches  map[string]string `json:"matches,omitempty"`
}

// StubInput defines model for StubInput.
type StubInput struct {
	Contains         map[string]interface{} `json:"contains,omitempty"`
	Equals           map[string]interface{} `json:"equals,omitempty"`
	IgnoreArrayOrder bool                   `json:"ignoreArrayOrder,omitempty"`
	Matches          map[string]interface{} `json:"matches,omitempty"`
}

// StubList defines model for StubList.
type StubList = []Stub

// StubOptions Optional behavior settings for a stub
type StubOptions struct {
	// Times Max number of matches; 0 = unlimited
	Times int `json:"times,omitempty"`
}

// StubOutput defines model for StubOutput.
type StubOutput struct {
	Code codes.Code             `json:"code,omitempty"`
	Data map[string]interface{} `json:"data,omitempty"`

	// Delay Delay before sending the response
	Delay gptypes.Duration `json:"delay,omitempty,omitzero"`

	// Details gRPC status details packed into google.protobuf.Any (each item must contain type URL in `type`)
	Details []StubOutput_Details_Item `json:"details,omitempty"`
	Error   string                    `json:"error,omitempty"`
	Headers map[string]string         `json:"headers,omitempty"`
	Stream  []map[string]interface{}  `json:"stream,omitempty"`
}

// StubOutput_Details_Item defines model for StubOutput.details.Item.
type StubOutput_Details_Item struct {
	// Type Full Any type URL (for example, type.googleapis.com/google.rpc.ErrorInfo)
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// VerifyError defines model for VerifyError.
type VerifyError struct {
	Actual   *int    `json:"actual,omitempty"`
	Expected *int    `json:"expected,omitempty"`
	Message  *string `json:"message,omitempty"`
}

// VerifyRequest defines model for VerifyRequest.
type VerifyRequest struct {
	ExpectedCount int    `json:"expectedCount"`
	Method        string `json:"method"`
	Service       string `json:"service"`
}

// AddStubJSONBody defines parameters for AddStub.
type AddStubJSONBody struct {
	union json.RawMessage
}

// McpMessageJSONRequestBody defines body for McpMessage for application/json ContentType.
type McpMessageJSONRequestBody = McpRequest

// AddStubJSONRequestBody defines body for AddStub for application/json ContentType.
type AddStubJSONRequestBody AddStubJSONBody

// BatchStubsDeleteJSONRequestBody defines body for BatchStubsDelete for application/json ContentType.
type BatchStubsDeleteJSONRequestBody = ListID

// SearchStubsJSONRequestBody defines body for SearchStubs for application/json ContentType.
type SearchStubsJSONRequestBody = SearchRequest

// VerifyCallsJSONRequestBody defines body for VerifyCalls for application/json ContentType.
type VerifyCallsJSONRequestBody = VerifyRequest

// Getter for additional properties for StubOutput_Details_Item. Returns the specified
// element and whether it was found
func (a StubOutput_Details_Item) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for StubOutput_Details_Item
func (a *StubOutput_Details_Item) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for StubOutput_Details_Item to handle AdditionalProperties
func (a *StubOutput_Details_Item) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := jsonUnmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["type"]; found {
		err = jsonUnmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := jsonUnmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for StubOutput_Details_Item to handle AdditionalProperties
func (a StubOutput_Details_Item) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsMcpID0 returns the union data inside the McpID as a McpID0
func (t McpID) AsMcpID0() (McpID0, error) {
	var body McpID0
	err := jsonUnmarshal(t.union, &body)
	return body, err
}

// FromMcpID0 overwrites any union data inside the McpID as the provided McpID0
func (t *McpID) FromMcpID0(v McpID0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMcpID0 performs a merge with any union data inside the McpID, using the provided McpID0
func (t *McpID) MergeMcpID0(v McpID0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMcpID1 returns the union data inside the McpID as a McpID1
func (t McpID) AsMcpID1() (McpID1, error) {
	var body McpID1
	err := jsonUnmarshal(t.union, &body)
	return body, err
}

// FromMcpID1 overwrites any union data inside the McpID as the provided McpID1
func (t *McpID) FromMcpID1(v McpID1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMcpID1 performs a merge with any union data inside the McpID, using the provided McpID1
func (t *McpID) MergeMcpID1(v McpID1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t McpID) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *McpID) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListDescriptors request
	ListDescriptors(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddDescriptorsWithBody request with any body
	AddDescriptorsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Liveness request
	Liveness(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Readiness request
	Readiness(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListHistory request
	ListHistory(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// McpInfo request
	McpInfo(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// McpMessageWithBody request with any body
	McpMessageWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	McpMessage(ctx context.Context, body McpMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ServicesList request
	ServicesList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteService request
	DeleteService(ctx context.Context, serviceID string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ServiceMethodsList request
	ServiceMethodsList(ctx context.Context, serviceID string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PurgeStubs request
	PurgeStubs(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListStubs request
	ListStubs(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddStubWithBody request with any body
	AddStubWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AddStub(ctx context.Context, body AddStubJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BatchStubsDeleteWithBody request with any body
	BatchStubsDeleteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	BatchStubsDelete(ctx context.Context, body BatchStubsDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SearchStubsWithBody request with any body
	SearchStubsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SearchStubs(ctx context.Context, body SearchStubsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListUnusedStubs request
	ListUnusedStubs(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListUsedStubs request
	ListUsedStubs(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteStubByID request
	DeleteStubByID(ctx context.Context, uuid ID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FindByID request
	FindByID(ctx context.Context, uuid ID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// VerifyCallsWithBody request with any body
	VerifyCallsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	VerifyCalls(ctx context.Context, body VerifyCallsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListDescriptors(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDescriptorsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddDescriptorsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddDescriptorsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Liveness(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLivenessRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Readiness(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReadinessRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListHistory(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListHistoryRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) McpInfo(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMcpInfoRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) McpMessageWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMcpMessageRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) McpMessage(ctx context.Context, body McpMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMcpMessageRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ServicesList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewServicesListRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteService(ctx context.Context, serviceID string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteServiceRequest(c.Server, serviceID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ServiceMethodsList(ctx context.Context, serviceID string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewServiceMethodsListRequest(c.Server, serviceID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PurgeStubs(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPurgeStubsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListStubs(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListStubsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddStubWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddStubRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddStub(ctx context.Context, body AddStubJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddStubRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BatchStubsDeleteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBatchStubsDeleteRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BatchStubsDelete(ctx context.Context, body BatchStubsDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBatchStubsDeleteRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SearchStubsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchStubsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SearchStubs(ctx context.Context, body SearchStubsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchStubsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListUnusedStubs(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListUnusedStubsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListUsedStubs(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListUsedStubsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteStubByID(ctx context.Context, uuid ID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteStubByIDRequest(c.Server, uuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindByID(ctx context.Context, uuid ID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindByIDRequest(c.Server, uuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) VerifyCallsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVerifyCallsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) VerifyCalls(ctx context.Context, body VerifyCallsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVerifyCallsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListDescriptorsRequest generates requests for ListDescriptors
func NewListDescriptorsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/descriptors")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddDescriptorsRequestWithBody generates requests for AddDescriptors with any type of body
func NewAddDescriptorsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/descriptors")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewLivenessRequest generates requests for Liveness
func NewLivenessRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health/liveness")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewReadinessRequest generates requests for Readiness
func NewReadinessRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health/readiness")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListHistoryRequest generates requests for ListHistory
func NewListHistoryRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/history")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewMcpInfoRequest generates requests for McpInfo
func NewMcpInfoRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/mcp")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewMcpMessageRequest calls the generic McpMessage builder with application/json body
func NewMcpMessageRequest(server string, body McpMessageJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewMcpMessageRequestWithBody(server, "application/json", bodyReader)
}

// NewMcpMessageRequestWithBody generates requests for McpMessage with any type of body
func NewMcpMessageRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/mcp")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewServicesListRequest generates requests for ServicesList
func NewServicesListRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/services")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteServiceRequest generates requests for DeleteService
func NewDeleteServiceRequest(server string, serviceID string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "serviceID", serviceID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/services/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewServiceMethodsListRequest generates requests for ServiceMethodsList
func NewServiceMethodsListRequest(server string, serviceID string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "serviceID", serviceID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/services/%s/methods", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPurgeStubsRequest generates requests for PurgeStubs
func NewPurgeStubsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stubs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListStubsRequest generates requests for ListStubs
func NewListStubsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stubs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddStubRequest calls the generic AddStub builder with application/json body
func NewAddStubRequest(server string, body AddStubJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAddStubRequestWithBody(server, "application/json", bodyReader)
}

// NewAddStubRequestWithBody generates requests for AddStub with any type of body
func NewAddStubRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stubs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewBatchStubsDeleteRequest calls the generic BatchStubsDelete builder with application/json body
func NewBatchStubsDeleteRequest(server string, body BatchStubsDeleteJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewBatchStubsDeleteRequestWithBody(server, "application/json", bodyReader)
}

// NewBatchStubsDeleteRequestWithBody generates requests for BatchStubsDelete with any type of body
func NewBatchStubsDeleteRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stubs/batchDelete")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewSearchStubsRequest calls the generic SearchStubs builder with application/json body
func NewSearchStubsRequest(server string, body SearchStubsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSearchStubsRequestWithBody(server, "application/json", bodyReader)
}

// NewSearchStubsRequestWithBody generates requests for SearchStubs with any type of body
func NewSearchStubsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stubs/search")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListUnusedStubsRequest generates requests for ListUnusedStubs
func NewListUnusedStubsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stubs/unused")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListUsedStubsRequest generates requests for ListUsedStubs
func NewListUsedStubsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stubs/used")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteStubByIDRequest generates requests for DeleteStubByID
func NewDeleteStubByIDRequest(server string, uuid ID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "uuid", uuid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stubs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFindByIDRequest generates requests for FindByID
func NewFindByIDRequest(server string, uuid ID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "uuid", uuid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stubs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewVerifyCallsRequest calls the generic VerifyCalls builder with application/json body
func NewVerifyCallsRequest(server string, body VerifyCallsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewVerifyCallsRequestWithBody(server, "application/json", bodyReader)
}

// NewVerifyCallsRequestWithBody generates requests for VerifyCalls with any type of body
func NewVerifyCallsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/verify")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListDescriptorsWithResponse request
	ListDescriptorsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDescriptorsResponse, error)

	// AddDescriptorsWithBodyWithResponse request with any body
	AddDescriptorsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddDescriptorsResponse, error)

	// LivenessWithResponse request
	LivenessWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*LivenessResponse, error)

	// ReadinessWithResponse request
	ReadinessWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ReadinessResponse, error)

	// ListHistoryWithResponse request
	ListHistoryWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListHistoryResponse, error)

	// McpInfoWithResponse request
	McpInfoWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*McpInfoResponse, error)

	// McpMessageWithBodyWithResponse request with any body
	McpMessageWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*McpMessageResponse, error)

	McpMessageWithResponse(ctx context.Context, body McpMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*McpMessageResponse, error)

	// ServicesListWithResponse request
	ServicesListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ServicesListResponse, error)

	// DeleteServiceWithResponse request
	DeleteServiceWithResponse(ctx context.Context, serviceID string, reqEditors ...RequestEditorFn) (*DeleteServiceResponse, error)

	// ServiceMethodsListWithResponse request
	ServiceMethodsListWithResponse(ctx context.Context, serviceID string, reqEditors ...RequestEditorFn) (*ServiceMethodsListResponse, error)

	// PurgeStubsWithResponse request
	PurgeStubsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PurgeStubsResponse, error)

	// ListStubsWithResponse request
	ListStubsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListStubsResponse, error)

	// AddStubWithBodyWithResponse request with any body
	AddStubWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddStubResponse, error)

	AddStubWithResponse(ctx context.Context, body AddStubJSONRequestBody, reqEditors ...RequestEditorFn) (*AddStubResponse, error)

	// BatchStubsDeleteWithBodyWithResponse request with any body
	BatchStubsDeleteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BatchStubsDeleteResponse, error)

	BatchStubsDeleteWithResponse(ctx context.Context, body BatchStubsDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*BatchStubsDeleteResponse, error)

	// SearchStubsWithBodyWithResponse request with any body
	SearchStubsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SearchStubsResponse, error)

	SearchStubsWithResponse(ctx context.Context, body SearchStubsJSONRequestBody, reqEditors ...RequestEditorFn) (*SearchStubsResponse, error)

	// ListUnusedStubsWithResponse request
	ListUnusedStubsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListUnusedStubsResponse, error)

	// ListUsedStubsWithResponse request
	ListUsedStubsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListUsedStubsResponse, error)

	// DeleteStubByIDWithResponse request
	DeleteStubByIDWithResponse(ctx context.Context, uuid ID, reqEditors ...RequestEditorFn) (*DeleteStubByIDResponse, error)

	// FindByIDWithResponse request
	FindByIDWithResponse(ctx context.Context, uuid ID, reqEditors ...RequestEditorFn) (*FindByIDResponse, error)

	// VerifyCallsWithBodyWithResponse request with any body
	VerifyCallsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*VerifyCallsResponse, error)

	VerifyCallsWithResponse(ctx context.Context, body VerifyCallsJSONRequestBody, reqEditors ...RequestEditorFn) (*VerifyCallsResponse, error)
}

type ListDescriptorsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DescriptorServiceIDs
}

// Status returns HTTPResponse.Status
func (r ListDescriptorsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDescriptorsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AddDescriptorsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AddDescriptorsResponse
}

// Status returns HTTPResponse.Status
func (r AddDescriptorsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddDescriptorsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type LivenessResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MessageOK
}

// Status returns HTTPResponse.Status
func (r LivenessResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LivenessResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ReadinessResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MessageOK
}

// Status returns HTTPResponse.Status
func (r ReadinessResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReadinessResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListHistoryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HistoryList
}

// Status returns HTTPResponse.Status
func (r ListHistoryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListHistoryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type McpInfoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *McpInfoResponse
}

// Status returns HTTPResponse.Status
func (r McpInfoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r McpInfoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type McpMessageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *McpResponse
}

// Status returns HTTPResponse.Status
func (r McpMessageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r McpMessageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ServicesListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Service
}

// Status returns HTTPResponse.Status
func (r ServicesListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ServicesListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteServiceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteServiceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteServiceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ServiceMethodsListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Method
}

// Status returns HTTPResponse.Status
func (r ServiceMethodsListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ServiceMethodsListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PurgeStubsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PurgeStubsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PurgeStubsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListStubsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *StubList
}

// Status returns HTTPResponse.Status
func (r ListStubsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListStubsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AddStubResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
}

// Status returns HTTPResponse.Status
func (r AddStubResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddStubResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BatchStubsDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r BatchStubsDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BatchStubsDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SearchStubsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SearchResponse
}

// Status returns HTTPResponse.Status
func (r SearchStubsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SearchStubsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListUnusedStubsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *StubList
}

// Status returns HTTPResponse.Status
func (r ListUnusedStubsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListUnusedStubsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListUsedStubsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *StubList
}

// Status returns HTTPResponse.Status
func (r ListUsedStubsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListUsedStubsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteStubByIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteStubByIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteStubByIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FindByIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Stub
}

// Status returns HTTPResponse.Status
func (r FindByIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindByIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type VerifyCallsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MessageOK
	JSON400      *VerifyError
}

// Status returns HTTPResponse.Status
func (r VerifyCallsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r VerifyCallsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListDescriptorsWithResponse request returning *ListDescriptorsResponse
func (c *ClientWithResponses) ListDescriptorsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDescriptorsResponse, error) {
	rsp, err := c.ListDescriptors(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDescriptorsResponse(rsp)
}

// AddDescriptorsWithBodyWithResponse request with arbitrary body returning *AddDescriptorsResponse
func (c *ClientWithResponses) AddDescriptorsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddDescriptorsResponse, error) {
	rsp, err := c.AddDescriptorsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddDescriptorsResponse(rsp)
}

// LivenessWithResponse request returning *LivenessResponse
func (c *ClientWithResponses) LivenessWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*LivenessResponse, error) {
	rsp, err := c.Liveness(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLivenessResponse(rsp)
}

// ReadinessWithResponse request returning *ReadinessResponse
func (c *ClientWithResponses) ReadinessWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ReadinessResponse, error) {
	rsp, err := c.Readiness(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReadinessResponse(rsp)
}

// ListHistoryWithResponse request returning *ListHistoryResponse
func (c *ClientWithResponses) ListHistoryWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListHistoryResponse, error) {
	rsp, err := c.ListHistory(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListHistoryResponse(rsp)
}

// McpInfoWithResponse request returning *McpInfoResponse
func (c *ClientWithResponses) McpInfoWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*McpInfoResponse, error) {
	rsp, err := c.McpInfo(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMcpInfoResponse(rsp)
}

// McpMessageWithBodyWithResponse request with arbitrary body returning *McpMessageResponse
func (c *ClientWithResponses) McpMessageWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*McpMessageResponse, error) {
	rsp, err := c.McpMessageWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMcpMessageResponse(rsp)
}

func (c *ClientWithResponses) McpMessageWithResponse(ctx context.Context, body McpMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*McpMessageResponse, error) {
	rsp, err := c.McpMessage(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMcpMessageResponse(rsp)
}

// ServicesListWithResponse request returning *ServicesListResponse
func (c *ClientWithResponses) ServicesListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ServicesListResponse, error) {
	rsp, err := c.ServicesList(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseServicesListResponse(rsp)
}

// DeleteServiceWithResponse request returning *DeleteServiceResponse
func (c *ClientWithResponses) DeleteServiceWithResponse(ctx context.Context, serviceID string, reqEditors ...RequestEditorFn) (*DeleteServiceResponse, error) {
	rsp, err := c.DeleteService(ctx, serviceID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteServiceResponse(rsp)
}

// ServiceMethodsListWithResponse request returning *ServiceMethodsListResponse
func (c *ClientWithResponses) ServiceMethodsListWithResponse(ctx context.Context, serviceID string, reqEditors ...RequestEditorFn) (*ServiceMethodsListResponse, error) {
	rsp, err := c.ServiceMethodsList(ctx, serviceID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseServiceMethodsListResponse(rsp)
}

// PurgeStubsWithResponse request returning *PurgeStubsResponse
func (c *ClientWithResponses) PurgeStubsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PurgeStubsResponse, error) {
	rsp, err := c.PurgeStubs(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePurgeStubsResponse(rsp)
}

// ListStubsWithResponse request returning *ListStubsResponse
func (c *ClientWithResponses) ListStubsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListStubsResponse, error) {
	rsp, err := c.ListStubs(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListStubsResponse(rsp)
}

// AddStubWithBodyWithResponse request with arbitrary body returning *AddStubResponse
func (c *ClientWithResponses) AddStubWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddStubResponse, error) {
	rsp, err := c.AddStubWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddStubResponse(rsp)
}

func (c *ClientWithResponses) AddStubWithResponse(ctx context.Context, body AddStubJSONRequestBody, reqEditors ...RequestEditorFn) (*AddStubResponse, error) {
	rsp, err := c.AddStub(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddStubResponse(rsp)
}

// BatchStubsDeleteWithBodyWithResponse request with arbitrary body returning *BatchStubsDeleteResponse
func (c *ClientWithResponses) BatchStubsDeleteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BatchStubsDeleteResponse, error) {
	rsp, err := c.BatchStubsDeleteWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBatchStubsDeleteResponse(rsp)
}

func (c *ClientWithResponses) BatchStubsDeleteWithResponse(ctx context.Context, body BatchStubsDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*BatchStubsDeleteResponse, error) {
	rsp, err := c.BatchStubsDelete(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBatchStubsDeleteResponse(rsp)
}

// SearchStubsWithBodyWithResponse request with arbitrary body returning *SearchStubsResponse
func (c *ClientWithResponses) SearchStubsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SearchStubsResponse, error) {
	rsp, err := c.SearchStubsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchStubsResponse(rsp)
}

func (c *ClientWithResponses) SearchStubsWithResponse(ctx context.Context, body SearchStubsJSONRequestBody, reqEditors ...RequestEditorFn) (*SearchStubsResponse, error) {
	rsp, err := c.SearchStubs(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchStubsResponse(rsp)
}

// ListUnusedStubsWithResponse request returning *ListUnusedStubsResponse
func (c *ClientWithResponses) ListUnusedStubsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListUnusedStubsResponse, error) {
	rsp, err := c.ListUnusedStubs(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListUnusedStubsResponse(rsp)
}

// ListUsedStubsWithResponse request returning *ListUsedStubsResponse
func (c *ClientWithResponses) ListUsedStubsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListUsedStubsResponse, error) {
	rsp, err := c.ListUsedStubs(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListUsedStubsResponse(rsp)
}

// DeleteStubByIDWithResponse request returning *DeleteStubByIDResponse
func (c *ClientWithResponses) DeleteStubByIDWithResponse(ctx context.Context, uuid ID, reqEditors ...RequestEditorFn) (*DeleteStubByIDResponse, error) {
	rsp, err := c.DeleteStubByID(ctx, uuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteStubByIDResponse(rsp)
}

// FindByIDWithResponse request returning *FindByIDResponse
func (c *ClientWithResponses) FindByIDWithResponse(ctx context.Context, uuid ID, reqEditors ...RequestEditorFn) (*FindByIDResponse, error) {
	rsp, err := c.FindByID(ctx, uuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindByIDResponse(rsp)
}

// VerifyCallsWithBodyWithResponse request with arbitrary body returning *VerifyCallsResponse
func (c *ClientWithResponses) VerifyCallsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*VerifyCallsResponse, error) {
	rsp, err := c.VerifyCallsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVerifyCallsResponse(rsp)
}

func (c *ClientWithResponses) VerifyCallsWithResponse(ctx context.Context, body VerifyCallsJSONRequestBody, reqEditors ...RequestEditorFn) (*VerifyCallsResponse, error) {
	rsp, err := c.VerifyCalls(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVerifyCallsResponse(rsp)
}

// ParseListDescriptorsResponse parses an HTTP response from a ListDescriptorsWithResponse call
func ParseListDescriptorsResponse(rsp *http.Response) (*ListDescriptorsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDescriptorsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DescriptorServiceIDs
		if err := jsonUnmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseAddDescriptorsResponse parses an HTTP response from a AddDescriptorsWithResponse call
func ParseAddDescriptorsResponse(rsp *http.Response) (*AddDescriptorsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddDescriptorsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AddDescriptorsResponse
		if err := jsonUnmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseLivenessResponse parses an HTTP response from a LivenessWithResponse call
func ParseLivenessResponse(rsp *http.Response) (*LivenessResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LivenessResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MessageOK
		if err := jsonUnmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseReadinessResponse parses an HTTP response from a ReadinessWithResponse call
func ParseReadinessResponse(rsp *http.Response) (*ReadinessResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReadinessResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MessageOK
		if err := jsonUnmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListHistoryResponse parses an HTTP response from a ListHistoryWithResponse call
func ParseListHistoryResponse(rsp *http.Response) (*ListHistoryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListHistoryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HistoryList
		if err := jsonUnmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseMcpInfoResponse parses an HTTP response from a McpInfoWithResponse call
func ParseMcpInfoResponse(rsp *http.Response) (*McpInfoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &McpInfoResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest McpInfoResponse
		if err := jsonUnmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseMcpMessageResponse parses an HTTP response from a McpMessageWithResponse call
func ParseMcpMessageResponse(rsp *http.Response) (*McpMessageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &McpMessageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest McpResponse
		if err := jsonUnmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseServicesListResponse parses an HTTP response from a ServicesListWithResponse call
func ParseServicesListResponse(rsp *http.Response) (*ServicesListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ServicesListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Service
		if err := jsonUnmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteServiceResponse parses an HTTP response from a DeleteServiceWithResponse call
func ParseDeleteServiceResponse(rsp *http.Response) (*DeleteServiceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteServiceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseServiceMethodsListResponse parses an HTTP response from a ServiceMethodsListWithResponse call
func ParseServiceMethodsListResponse(rsp *http.Response) (*ServiceMethodsListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ServiceMethodsListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Method
		if err := jsonUnmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePurgeStubsResponse parses an HTTP response from a PurgeStubsWithResponse call
func ParsePurgeStubsResponse(rsp *http.Response) (*PurgeStubsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PurgeStubsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseListStubsResponse parses an HTTP response from a ListStubsWithResponse call
func ParseListStubsResponse(rsp *http.Response) (*ListStubsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListStubsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest StubList
		if err := jsonUnmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseAddStubResponse parses an HTTP response from a AddStubWithResponse call
func ParseAddStubResponse(rsp *http.Response) (*AddStubResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddStubResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := jsonUnmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseBatchStubsDeleteResponse parses an HTTP response from a BatchStubsDeleteWithResponse call
func ParseBatchStubsDeleteResponse(rsp *http.Response) (*BatchStubsDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BatchStubsDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseSearchStubsResponse parses an HTTP response from a SearchStubsWithResponse call
func ParseSearchStubsResponse(rsp *http.Response) (*SearchStubsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SearchStubsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SearchResponse
		if err := jsonUnmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListUnusedStubsResponse parses an HTTP response from a ListUnusedStubsWithResponse call
func ParseListUnusedStubsResponse(rsp *http.Response) (*ListUnusedStubsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListUnusedStubsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest StubList
		if err := jsonUnmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListUsedStubsResponse parses an HTTP response from a ListUsedStubsWithResponse call
func ParseListUsedStubsResponse(rsp *http.Response) (*ListUsedStubsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListUsedStubsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest StubList
		if err := jsonUnmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteStubByIDResponse parses an HTTP response from a DeleteStubByIDWithResponse call
func ParseDeleteStubByIDResponse(rsp *http.Response) (*DeleteStubByIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteStubByIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseFindByIDResponse parses an HTTP response from a FindByIDWithResponse call
func ParseFindByIDResponse(rsp *http.Response) (*FindByIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindByIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Stub
		if err := jsonUnmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseVerifyCallsResponse parses an HTTP response from a VerifyCallsWithResponse call
func ParseVerifyCallsResponse(rsp *http.Response) (*VerifyCallsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &VerifyCallsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MessageOK
		if err := jsonUnmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest VerifyError
		if err := jsonUnmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}
